name: App
include:
  - app/addons/addons.yml
targets:
  App:
    type: application
    platform: iOS
    deploymentTarget: 14.0
    info:
      path: app/Info.plist
      properties:
        CFBundleIdentifier: to.holepunch.bare.ios
    dependencies:
      - framework: app/frameworks/BareKit.xcframework
    sources:
      - path: app/AppDelegate.h
      - path: app/AppDelegate.m
      - path: app/app.bundle
        optional: true
      - path: app/app.js
      - path: app/main.m
    scheme:
      preActions:
        - script: |
            npx bare-link \
              --target ios-arm64 \
              --target ios-arm64-simulator \
              --target ios-x64-simulator \
              --out ${PWD}/app/addons \
              ${PWD}
        - script: |
            npx bare-pack \
              --platform ios \
              --linked \
              --out ${PWD}/app/app.bundle \
              ${PWD}/app/app.js
