name: App
include:
  - app/addons/addons.yml
packages:
  BareKit:
    url: https://github.com/holepunchto/bare-kit-swift
    branch: main
targets:
  App:
    type: application
    platform: iOS
    deploymentTarget: 14.0
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: to.holepunch.bare.ios
        SWIFT_VERSION: 5.0
        CODE_SIGN_ENTITLEMENTS: app/App.entitlements
    info:
      path: app/Info.plist
    dependencies:
      - framework: app/frameworks/BareKit.xcframework
      - package: BareKit
      - target: NotificationServiceExtension
    sources:
      - path: app/App.swift
      - path: app/app.js
      - path: app/app.bundle
        optional: true
    scheme:
      preActions:
        - name: Link
          script: |
            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-link" \
              --target ios-arm64 \
              --target ios-arm64-simulator \
              --target ios-x64-simulator \
              --out ${PWD}/app/addons \
              ${PWD}
        - name: Pack
          script: |
            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-pack" \
              --target ios-arm64 \
              --target ios-arm64-simulator \
              --target ios-x64-simulator \
              --linked \
              --base ${PWD} \
              --out ${PWD}/app/app.bundle \
              ${PWD}/app/app.js
            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-pack" \
              --target ios-arm64 \
              --target ios-arm64-simulator \
              --target ios-x64-simulator \
              --linked \
              --base ${PWD} \
              --out ${PWD}/app/push.bundle \
              ${PWD}/app/push.js
  NotificationServiceExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: 14.0
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: to.holepunch.bare.ios.NotificationServiceExtension
        SWIFT_VERSION: 5.0
        CODE_SIGN_ENTITLEMENTS: app/NotificationServiceExtension.entitlements
    info:
      path: app/NotificationServiceExtension.Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.usernotifications.service
          NSExtensionPrincipalClass: NotificationServiceExtension.NotificationService
    dependencies:
      - framework: app/frameworks/BareKit.xcframework
      - package: BareKit
    sources:
      - path: app/NotificationService.swift
      - path: app/push.js
      - path: app/push.bundle
        optional: true
