name: App
include:
  - app/addons/addons.yml
targets:
  App:
    type: application
    platform: iOS
    deploymentTarget: 14.0
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: to.holepunch.bare.ios
        SWIFT_VERSION: 5.0
        SWIFT_OBJC_BRIDGING_HEADER: app/App-Bridging-Header.h
    info:
      path: app/Info.plist
    dependencies:
      - framework: app/frameworks/BareKit.xcframework
    sources:
      - path: app/App.swift
      - path: app/App-Bridging-Header.h
      - path: app/app.js
      - path: app/app.bundle
        optional: true
    scheme:
      preActions:
        - name: Link
          script: |
            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-link" \
              --target ios-arm64 \
              --target ios-arm64-simulator \
              --target ios-x64-simulator \
              --out ${PWD}/app/addons \
              ${PWD}
        - name: Pack
          script: |
            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-pack" \
              --target ios-arm64 \
              --target ios-arm64-simulator \
              --target ios-x64-simulator \
              --linked \
              --base ${PWD} \
              --out ${PWD}/app/app.bundle \
              ${PWD}/app/app.js
