name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        include:
          - os: macos-14
            platform: ios
            arch: arm64
          - os: macos-14
            platform: ios
            arch: arm64
            tags: -simulator
            flags: --simulator
          - os: macos-14
            platform: ios
            arch: x64
            tags: -simulator
            flags: --simulator
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: bare install xcodegen
      - run: npm install
      - run: |
          gh release download --repo holepunchto/bare-kit v1.0.0
          unzip prebuilds.zip "ios/*" -d prebuilds/
          mv prebuilds/ios/BareKit.xcframework app/frameworks/
        env:
          GH_TOKEN: ${{ github.token }}
      - run: xcodegen generate
      - run: xcodebuild build CODE_SIGNING_ALLOWED=NO
