name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        include:
        - os: macos-14
          platform: ios
          arch: arm64
        - os: macos-14
          platform: ios
          arch: arm64
          tags: -simulator
          flags: --simulator
        - os: macos-14
          platform: ios
          arch: x64
          tags: -simulator
          flags: --simulator
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: build/_drive
        key: corestore-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: npm install -g bare-make
    - run: bare-make generate --platform ${{ matrix.platform }} --arch ${{ matrix.arch }} ${{ matrix.flags }} --debug
    - run: bare-make build
