name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: ios
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: brew install xcodegen
      - run: npm install
      - run: |
          gh release download --repo holepunchto/bare-kit v1.2.0
          unzip prebuilds.zip "ios/*" -d prebuilds/
          mv prebuilds/ios/BareKit.xcframework app/frameworks/
        env:
          GH_TOKEN: ${{ github.token }}
      - run: xcodegen generate
      - run: xcodebuild -scheme App build CODE_SIGNING_ALLOWED=NO
